/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.admissionforpatan;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Date;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Programming-learning
 */
public class Attendance extends javax.swing.JFrame {

    /**
     * Creates new form Attendance
     */
    public Attendance() {
        initComponents();
        ImageIcon img=new ImageIcon("src\\main\\icons\\file.png");
        setIconImage(img.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel13 = new javax.swing.JPanel();
        jSeparator24 = new javax.swing.JSeparator();
        jSeparator45 = new javax.swing.JSeparator();
        jSeparator44 = new javax.swing.JSeparator();
        jSeparator46 = new javax.swing.JSeparator();
        jSeparator26 = new javax.swing.JSeparator();
        jSeparator25 = new javax.swing.JSeparator();
        jLabel42 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jSeparator33 = new javax.swing.JSeparator();
        jSeparator34 = new javax.swing.JSeparator();
        jSeparator36 = new javax.swing.JSeparator();
        jSeparator49 = new javax.swing.JSeparator();
        jPanel12 = new javax.swing.JPanel();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator41 = new javax.swing.JSeparator();
        jSeparator43 = new javax.swing.JSeparator();
        jSeparator42 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        slid = new javax.swing.JSlider();
        batch = new javax.swing.JTextField();
        section = new javax.swing.JTextField();
        prevall = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        faculty = new javax.swing.JTextField();
        jSeparator37 = new javax.swing.JSeparator();
        jSeparator38 = new javax.swing.JSeparator();
        jSeparator39 = new javax.swing.JSeparator();
        jSeparator40 = new javax.swing.JSeparator();
        jSeparator47 = new javax.swing.JSeparator();
        jSeparator48 = new javax.swing.JSeparator();
        jSeparator35 = new javax.swing.JSeparator();
        jSeparator50 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(300, 300, 300, 300));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 0, 255));
        jLabel37.setText("Attandance Section");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 11, 159, -1));

        jTabbedPane3.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane3.setForeground(new java.awt.Color(0, 0, 255));
        jTabbedPane3.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane3.setFocusable(false);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator24.setForeground(new java.awt.Color(0, 0, 255));
        jPanel13.add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 139, 150, 10));

        jSeparator45.setBackground(new java.awt.Color(0, 0, 255));
        jSeparator45.setForeground(new java.awt.Color(0, 0, 255));
        jSeparator45.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel13.add(jSeparator45, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 10, 30));

        jSeparator44.setBackground(new java.awt.Color(0, 0, 255));
        jSeparator44.setForeground(new java.awt.Color(0, 0, 255));
        jSeparator44.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel13.add(jSeparator44, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 10, 30));

        jSeparator46.setBackground(new java.awt.Color(0, 0, 255));
        jSeparator46.setForeground(new java.awt.Color(0, 0, 255));
        jPanel13.add(jSeparator46, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 80, 10));

        jSeparator26.setForeground(new java.awt.Color(0, 0, 255));
        jPanel13.add(jSeparator26, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 79, 140, 10));

        jSeparator25.setForeground(new java.awt.Color(0, 0, 255));
        jPanel13.add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 109, 150, 10));

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 0, 255));
        jLabel42.setText("Name");
        jPanel13.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 59, 70, -1));

        jLabel48.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(0, 0, 255));
        jLabel48.setText("Shift");
        jPanel13.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 89, 70, -1));

        jLabel49.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(0, 0, 255));
        jLabel49.setText("Depart");
        jPanel13.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 119, 70, -1));

        jLabel50.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(0, 51, 255));
        jLabel50.setText("Submit");
        jLabel50.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel13.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 162, 70, 30));

        jSeparator33.setBackground(new java.awt.Color(0, 0, 255));
        jSeparator33.setForeground(new java.awt.Color(0, 0, 255));
        jSeparator33.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel13.add(jSeparator33, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, -10, 10, 200));

        jSeparator34.setBackground(new java.awt.Color(0, 0, 255));
        jSeparator34.setForeground(new java.awt.Color(0, 0, 255));
        jSeparator34.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel13.add(jSeparator34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 10, 200));

        jSeparator36.setBackground(new java.awt.Color(0, 0, 255));
        jSeparator36.setForeground(new java.awt.Color(0, 0, 255));
        jPanel13.add(jSeparator36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 300, 10));

        jSeparator49.setBackground(new java.awt.Color(0, 0, 255));
        jSeparator49.setForeground(new java.awt.Color(0, 0, 255));
        jPanel13.add(jSeparator49, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 10));

        jTabbedPane3.addTab("Teacher", jPanel13);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setForeground(new java.awt.Color(0, 0, 255));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator19.setForeground(new java.awt.Color(0, 0, 255));
        jPanel12.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 110, 10));

        jSeparator41.setBackground(new java.awt.Color(0, 0, 255));
        jSeparator41.setForeground(new java.awt.Color(0, 0, 255));
        jSeparator41.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel12.add(jSeparator41, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 10, 30));

        jSeparator43.setBackground(new java.awt.Color(0, 0, 255));
        jSeparator43.setForeground(new java.awt.Color(0, 0, 255));
        jPanel12.add(jSeparator43, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 80, 10));

        jSeparator42.setBackground(new java.awt.Color(0, 0, 255));
        jSeparator42.setForeground(new java.awt.Color(0, 0, 255));
        jSeparator42.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel12.add(jSeparator42, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 10, 30));

        jSeparator17.setForeground(new java.awt.Color(0, 0, 255));
        jPanel12.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 110, 10));

        jSeparator18.setForeground(new java.awt.Color(0, 0, 255));
        jPanel12.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 110, 10));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 255));
        jLabel25.setText("Submit");
        jLabel25.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 255))); // NOI18N
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });
        jPanel12.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 60, 30));

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 0, 255));
        jLabel39.setText("Faculty");
        jPanel12.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 70, -1));

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 0, 255));
        jLabel40.setText("Present:");
        jPanel12.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 70, -1));

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 0, 255));
        jLabel41.setText("Section: ");
        jPanel12.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 70, -1));

        slid.setBackground(new java.awt.Color(255, 255, 255));
        slid.setForeground(new java.awt.Color(0, 0, 255));
        slid.setMaximum(35);
        slid.setPaintLabels(true);
        slid.setPaintTicks(true);
        slid.setSnapToTicks(true);
        slid.setToolTipText("Slide and choose");
        slid.setValue(0);
        slid.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slidStateChanged(evt);
            }
        });
        jPanel12.add(slid, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 180, -1));

        batch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        batch.setForeground(new java.awt.Color(0, 0, 255));
        batch.setBorder(null);
        batch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batchActionPerformed(evt);
            }
        });
        jPanel12.add(batch, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 110, 30));

        section.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        section.setForeground(new java.awt.Color(0, 0, 255));
        section.setBorder(null);
        jPanel12.add(section, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 110, 30));

        prevall.setEditable(false);
        prevall.setBackground(new java.awt.Color(255, 255, 255));
        prevall.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        prevall.setForeground(new java.awt.Color(0, 0, 255));
        prevall.setText("0");
        prevall.setBorder(null);
        prevall.setFocusable(false);
        prevall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevallActionPerformed(evt);
            }
        });
        jPanel12.add(prevall, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 108, 30, 40));

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(0, 0, 255));
        jLabel43.setText("Batch: ");
        jPanel12.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 70, -1));

        faculty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        faculty.setForeground(new java.awt.Color(0, 0, 255));
        faculty.setBorder(null);
        jPanel12.add(faculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 110, 30));

        jSeparator37.setBackground(new java.awt.Color(0, 0, 255));
        jSeparator37.setForeground(new java.awt.Color(0, 0, 255));
        jPanel12.add(jSeparator37, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 10));

        jSeparator38.setBackground(new java.awt.Color(0, 0, 255));
        jSeparator38.setForeground(new java.awt.Color(0, 0, 255));
        jSeparator38.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel12.add(jSeparator38, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 10, 190));

        jSeparator39.setBackground(new java.awt.Color(0, 0, 255));
        jSeparator39.setForeground(new java.awt.Color(0, 0, 255));
        jPanel12.add(jSeparator39, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 300, 10));

        jSeparator40.setBackground(new java.awt.Color(0, 0, 255));
        jSeparator40.setForeground(new java.awt.Color(0, 0, 255));
        jSeparator40.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel12.add(jSeparator40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 10, 200));

        jTabbedPane3.addTab("Student", jPanel12);

        jPanel1.add(jTabbedPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 44, 310, 225));

        jSeparator47.setBackground(new java.awt.Color(0, 0, 255));
        jSeparator47.setForeground(new java.awt.Color(0, 0, 255));
        jSeparator47.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator47, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 10, 200));

        jSeparator48.setBackground(new java.awt.Color(0, 0, 255));
        jSeparator48.setForeground(new java.awt.Color(0, 0, 255));
        jSeparator48.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator48, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, -10, 10, 70));

        jSeparator35.setBackground(new java.awt.Color(0, 0, 255));
        jSeparator35.setForeground(new java.awt.Color(0, 0, 255));
        jPanel1.add(jSeparator35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 58, 300, -1));

        jSeparator50.setBackground(new java.awt.Color(0, 0, 255));
        jSeparator50.setForeground(new java.awt.Color(0, 0, 255));
        jPanel1.add(jSeparator50, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void slidStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slidStateChanged
        // TODO add your handling code here:
        int prevalue=slid.getValue();
        prevall.setText(String.valueOf(prevalue));

    }//GEN-LAST:event_slidStateChanged

    private void prevallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevallActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prevallActionPerformed
String up=null;
    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        // TODO add your handling code here:
        //RECOGNIZE THE USER//////////////////////////////
        try {
            File frchstu = new File("D:\\Patan_APP\\Admin-control-settings\\current login.txt");
            try (BufferedReader fr = new BufferedReader(new FileReader(frchstu))) {
                if (frchstu.exists()) {
                    String strLine;
                        up=fr.readLine();
                }
                fr.close();
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Status.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Status.class.getName()).log(Level.SEVERE, null, ex);
        }  
        //store present students//////////////////////////
        File f1=new File("D:\\Patan_APP/Admin-control-settings/"+up+"/File/Attendance/Students_present/batch"+batch.getText()+"/"+section.getText());
        File f3 = new File("D:\\Patan_APP\\Admin-control-settings\\"+up+"\\Attendance\\Student_present"+Date.valueOf(LocalDate.now())+".txt");
        if(!f1.exists()){
        f1.mkdirs();}
        if(!f3.exists()){
        try {
            f3.createNewFile();
        } catch (IOException ex) {
            Logger.getLogger(Attendance.class.getName()).log(Level.SEVERE, null, ex);
        }}
        
        File f2=new File("D:\\Patan_APP/Admin-control-settings/"+up+"/File/Attendance/Students_present/batch"+batch.getText()+"/"+section.getText()+"/"+Date.valueOf(LocalDate.now())+".txt");
        if(f2.exists()){
        try {
            f2.createNewFile();
        } catch (IOException ex) {
            Logger.getLogger(Attendance.class.getName()).log(Level.SEVERE, null, ex);
        }}
        
        try {
            try (PrintWriter pw = new PrintWriter(f2)) {
                pw.write(slid.getValue());
                pw.close();
            }
            }
        catch (FileNotFoundException ex) {
            Logger.getLogger(Attendance.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            int co;
            try (FileReader fr = new FileReader(f3)) {
                co = fr.read()-48;
            }
            try (BufferedReader pw = new BufferedReader(new FileReader(f3))) {
                
            }   catch (IOException ex){
                Logger.getLogger(Attendance.class.getName()).log(Level.SEVERE, null, ex);
            }
            try (PrintWriter pw = new PrintWriter(f3)) {
                pw.write(slid.getValue()+co);
                pw.close();
            }
            }
        catch (FileNotFoundException ex) {
            Logger.getLogger(Attendance.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Attendance.class.getName()).log(Level.SEVERE, null, ex);
        }
 
    }//GEN-LAST:event_jLabel25MouseClicked
int c;
    private void batchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_batchActionPerformed

    /**
     * //@param args the command line arguments
     */
    public static void mainAttendance() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Attendance().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField batch;
    private javax.swing.JTextField faculty;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator33;
    private javax.swing.JSeparator jSeparator34;
    private javax.swing.JSeparator jSeparator35;
    private javax.swing.JSeparator jSeparator36;
    private javax.swing.JSeparator jSeparator37;
    private javax.swing.JSeparator jSeparator38;
    private javax.swing.JSeparator jSeparator39;
    private javax.swing.JSeparator jSeparator40;
    private javax.swing.JSeparator jSeparator41;
    private javax.swing.JSeparator jSeparator42;
    private javax.swing.JSeparator jSeparator43;
    private javax.swing.JSeparator jSeparator44;
    private javax.swing.JSeparator jSeparator45;
    private javax.swing.JSeparator jSeparator46;
    private javax.swing.JSeparator jSeparator47;
    private javax.swing.JSeparator jSeparator48;
    private javax.swing.JSeparator jSeparator49;
    private javax.swing.JSeparator jSeparator50;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextField prevall;
    private javax.swing.JTextField section;
    private javax.swing.JSlider slid;
    // End of variables declaration//GEN-END:variables
}
