/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.admissionforpatan;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Date;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Programming-learning
 */
public class Attendance extends javax.swing.JFrame {

    /**
     * Creates new form Attendance
     */
    public Attendance() {
        initComponents();
        ImageIcon img=new ImageIcon("src\\main\\icons\\file.png");
        setIconImage(img.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel13 = new javax.swing.JPanel();
        jSeparator24 = new javax.swing.JSeparator();
        jSeparator26 = new javax.swing.JSeparator();
        jSeparator25 = new javax.swing.JSeparator();
        jLabel42 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        slid = new javax.swing.JSlider();
        batch = new javax.swing.JTextField();
        section = new javax.swing.JTextField();
        prevall = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        faculty = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(300, 300, 300, 300));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 0, 255));
        jLabel37.setText("Attandance Section");

        jTabbedPane3.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane3.setForeground(new java.awt.Color(0, 0, 255));
        jTabbedPane3.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane3.setFocusable(false);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator24.setForeground(new java.awt.Color(0, 0, 255));
        jPanel13.add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 139, 150, 10));

        jSeparator26.setForeground(new java.awt.Color(0, 0, 255));
        jPanel13.add(jSeparator26, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 79, 140, 10));

        jSeparator25.setForeground(new java.awt.Color(0, 0, 255));
        jPanel13.add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 109, 150, 10));

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 0, 255));
        jLabel42.setText("Name");
        jPanel13.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 59, 70, -1));

        jLabel48.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(0, 0, 255));
        jLabel48.setText("Shift");
        jPanel13.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 89, 70, -1));

        jLabel49.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(0, 0, 255));
        jLabel49.setText("Depart");
        jPanel13.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 119, 70, -1));

        jLabel50.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(0, 51, 255));
        jLabel50.setText("Submit");
        jLabel50.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel13.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 159, 70, -1));

        jTabbedPane3.addTab("Teacher", jPanel13);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setForeground(new java.awt.Color(0, 0, 255));
        jPanel12.setLayout(null);

        jSeparator19.setForeground(new java.awt.Color(0, 0, 255));
        jPanel12.add(jSeparator19);
        jSeparator19.setBounds(90, 80, 110, 10);

        jSeparator17.setForeground(new java.awt.Color(0, 0, 255));
        jPanel12.add(jSeparator17);
        jSeparator17.setBounds(90, 50, 110, 10);

        jSeparator18.setForeground(new java.awt.Color(0, 0, 255));
        jPanel12.add(jSeparator18);
        jSeparator18.setBounds(90, 110, 110, 10);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 255));
        jLabel25.setText("Submit");
        jLabel25.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 255))); // NOI18N
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });
        jPanel12.add(jLabel25);
        jLabel25.setBounds(130, 150, 100, 22);

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 0, 255));
        jLabel39.setText("Faculty");
        jPanel12.add(jLabel39);
        jLabel39.setBounds(20, 30, 70, 22);

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 0, 255));
        jLabel40.setText("Present:");
        jPanel12.add(jLabel40);
        jLabel40.setBounds(20, 120, 70, 22);

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 0, 255));
        jLabel41.setText("Section: ");
        jPanel12.add(jLabel41);
        jLabel41.setBounds(20, 90, 70, 22);

        slid.setBackground(new java.awt.Color(255, 255, 255));
        slid.setForeground(new java.awt.Color(0, 0, 255));
        slid.setMaximum(35);
        slid.setPaintLabels(true);
        slid.setPaintTicks(true);
        slid.setSnapToTicks(true);
        slid.setToolTipText("Slide and choose");
        slid.setValue(0);
        slid.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slidStateChanged(evt);
            }
        });
        jPanel12.add(slid);
        slid.setBounds(90, 120, 180, 31);

        batch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        batch.setForeground(new java.awt.Color(0, 0, 255));
        batch.setBorder(null);
        batch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batchActionPerformed(evt);
            }
        });
        jPanel12.add(batch);
        batch.setBounds(90, 50, 110, 30);

        section.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        section.setForeground(new java.awt.Color(0, 0, 255));
        section.setBorder(null);
        jPanel12.add(section);
        section.setBounds(90, 80, 110, 30);

        prevall.setEditable(false);
        prevall.setBackground(new java.awt.Color(255, 255, 255));
        prevall.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        prevall.setForeground(new java.awt.Color(0, 0, 255));
        prevall.setText("0");
        prevall.setFocusable(false);
        prevall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevallActionPerformed(evt);
            }
        });
        jPanel12.add(prevall);
        prevall.setBounds(270, 120, 30, 28);

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(0, 0, 255));
        jLabel43.setText("Batch: ");
        jPanel12.add(jLabel43);
        jLabel43.setBounds(20, 60, 70, 22);

        faculty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        faculty.setForeground(new java.awt.Color(0, 0, 255));
        faculty.setBorder(null);
        jPanel12.add(faculty);
        faculty.setBounds(90, 20, 110, 30);

        jTabbedPane3.addTab("Student", jPanel12);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void slidStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slidStateChanged
        // TODO add your handling code here:
        int prevalue=slid.getValue();
        prevall.setText(String.valueOf(prevalue));

    }//GEN-LAST:event_slidStateChanged

    private void prevallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevallActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prevallActionPerformed
String up=null;
    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        // TODO add your handling code here:
        //RECOGNIZE THE USER//////////////////////////////
        try {
            File frchstu = new File("D:\\Patan_APP\\Admin-control-settings\\current login.txt");
            try (BufferedReader fr = new BufferedReader(new FileReader(frchstu))) {
                if (frchstu.exists()) {
                    String strLine;
                        up=fr.readLine();
                }
                fr.close();
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Status.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Status.class.getName()).log(Level.SEVERE, null, ex);
        }  
        //store present students//////////////////////////
        File f1=new File("D:\\Patan_APP/Admin-control-settings/"+up+"/File/Attendance/Students_present/batch"+batch.getText()+"/"+section.getText());
        File f3 = new File("D:\\Patan_APP\\Admin-control-settings\\"+up+"\\Attendance\\Student_present"+Date.valueOf(LocalDate.now())+".txt");
        if(!f1.exists()){
        f1.mkdirs();}
        if(!f3.exists()){
        try {
            f3.createNewFile();
        } catch (IOException ex) {
            Logger.getLogger(Attendance.class.getName()).log(Level.SEVERE, null, ex);
        }}
        
        File f2=new File("D:\\Patan_APP/Admin-control-settings/"+up+"/File/Attendance/Students_present/batch"+batch.getText()+"/"+section.getText()+"/"+Date.valueOf(LocalDate.now())+".txt");
        if(f2.exists()){
        try {
            f2.createNewFile();
        } catch (IOException ex) {
            Logger.getLogger(Attendance.class.getName()).log(Level.SEVERE, null, ex);
        }}
        
        try {
            try (PrintWriter pw = new PrintWriter(f2)) {
                pw.write(slid.getValue());
                pw.close();
            }
            }
        catch (FileNotFoundException ex) {
            Logger.getLogger(Attendance.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            int co;
            try (FileReader fr = new FileReader(f3)) {
                co = fr.read()-48;
            }
            try (BufferedReader pw = new BufferedReader(new FileReader(f3))) {
                
            }   catch (IOException ex){
                Logger.getLogger(Attendance.class.getName()).log(Level.SEVERE, null, ex);
            }
            try (PrintWriter pw = new PrintWriter(f3)) {
                pw.write(slid.getValue()+co);
                pw.close();
            }
            }
        catch (FileNotFoundException ex) {
            Logger.getLogger(Attendance.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Attendance.class.getName()).log(Level.SEVERE, null, ex);
        }
 
    }//GEN-LAST:event_jLabel25MouseClicked
int c;
    private void batchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_batchActionPerformed

    /**
     * //@param args the command line arguments
     */
    public static void mainAttendance() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Attendance().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField batch;
    private javax.swing.JTextField faculty;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextField prevall;
    private javax.swing.JTextField section;
    private javax.swing.JSlider slid;
    // End of variables declaration//GEN-END:variables
}
