/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.admissionforpatan;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Programming-learning
 */
public class Profile extends javax.swing.JFrame {

    /**
     * Creates new form Profile
     */
    public Profile() {
        
        initComponents();
        ImageIcon img=new ImageIcon("src\\main\\icons\\Login Manager.png");
        setIconImage(img.getImage());
        up_changer.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        up_changer = new javax.swing.JPanel();
        nup_text = new javax.swing.JLabel();
        nup = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        nup_text1 = new javax.swing.JLabel();
        oup = new javax.swing.JTextField();
        nup_text2 = new javax.swing.JLabel();
        ous = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        errch = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        position = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(250, 250, 250, 250));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jPanel2ComponentAdded(evt);
            }
        });
        jPanel2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel2ComponentShown(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        up_changer.setBackground(new java.awt.Color(255, 255, 255));
        up_changer.setLayout(null);

        nup_text.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nup_text.setForeground(new java.awt.Color(0, 0, 204));
        nup_text.setText("New Username");
        up_changer.add(nup_text);
        nup_text.setBounds(10, 80, 90, 40);

        nup.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nup.setForeground(new java.awt.Color(0, 0, 204));
        nup.setCaretColor(new java.awt.Color(0, 0, 255));
        nup.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nup.setSelectionColor(new java.awt.Color(102, 102, 255));
        up_changer.add(nup);
        nup.setBounds(100, 90, 110, 20);
        up_changer.add(jSeparator6);
        jSeparator6.setBounds(100, 30, 110, 10);
        up_changer.add(jSeparator19);
        jSeparator19.setBounds(100, 70, 110, 10);
        up_changer.add(jSeparator20);
        jSeparator20.setBounds(100, 110, 110, 10);

        nup_text1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nup_text1.setForeground(new java.awt.Color(0, 0, 204));
        nup_text1.setText("Old Password");
        up_changer.add(nup_text1);
        nup_text1.setBounds(10, 50, 90, 20);

        oup.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        oup.setForeground(new java.awt.Color(0, 0, 204));
        oup.setCaretColor(new java.awt.Color(0, 0, 255));
        oup.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        oup.setSelectionColor(new java.awt.Color(102, 102, 255));
        up_changer.add(oup);
        oup.setBounds(100, 50, 110, 20);

        nup_text2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nup_text2.setForeground(new java.awt.Color(0, 0, 204));
        nup_text2.setText("Old Username");
        up_changer.add(nup_text2);
        nup_text2.setBounds(10, 0, 80, 40);

        ous.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ous.setForeground(new java.awt.Color(0, 0, 204));
        ous.setCaretColor(new java.awt.Color(0, 0, 255));
        ous.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ous.setSelectionColor(new java.awt.Color(102, 102, 255));
        ous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ousActionPerformed(evt);
            }
        });
        up_changer.add(ous);
        ous.setBounds(100, 10, 110, 20);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 204));
        jButton2.setText("OK");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        up_changer.add(jButton2);
        jButton2.setBounds(160, 120, 50, 20);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 204));
        jButton3.setText("Cancel");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        up_changer.add(jButton3);
        jButton3.setBounds(70, 120, 70, 20);

        jPanel2.add(up_changer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 220, 165));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 102, 255));
        jLabel24.setText("Change Password");
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 110, 20));

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 204));
        jLabel31.setText("By: Sijan Bhandari");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 200, 50));
        jPanel2.add(errch, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 140, 20));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 102, 255));
        jLabel23.setText("Change Username");
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 120, 20));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Profile");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 90, -1));

        name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name.setForeground(new java.awt.Color(0, 0, 204));
        name.setText("Name:");
        jPanel2.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        position.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        position.setForeground(new java.awt.Color(0, 0, 204));
        position.setText("Position:");
        jPanel2.add(position, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setText("X");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 20, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        // TODO add your handling code here:
        up_changer.setVisible(true);
        nup_text.setText("New Password");
        user = 0;
    }//GEN-LAST:event_jLabel24MouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        // TODO add your handling code here:

        nup_text.setText("New Username");
        up_changer.setVisible(true);
        user = 1;
    }//GEN-LAST:event_jLabel23MouseClicked
int user=0;
    private void jPanel2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel2ComponentShown
        // TODO add your handling code here:
        // up_changer.setVisible(false);
        
    }//GEN-LAST:event_jPanel2ComponentShown

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked

        up_changer.setVisible(false);
        if (user == 1) {
            new userChanger();
        } else {

            new passChanger();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void ousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ousActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ousActionPerformed

    private void jPanel2ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jPanel2ComponentAdded
        // TODO add your handling code here:
//recognize user

//read user's name
         try {
            File frchstu = new File("D:\\Patan_APP\\Admin-control-settings\\Profile.txt");
            try (BufferedReader fr = new BufferedReader(new FileReader(frchstu))) {
                if (frchstu.exists()) {
                        name.setText("Name: "+fr.readLine());
                        position.setText("Position:"+fr.readLine());
                    
                }
                fr.close();
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Status.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Status.class.getName()).log(Level.SEVERE, null, ex);
        }    
//read user's profile        
    }//GEN-LAST:event_jPanel2ComponentAdded

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        up_changer.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed
String up;
    /**
     * //@param args the command line arguments
     */
    public static void mainpro() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Profile().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nup;
    private javax.swing.JLabel nup_text;
    private javax.swing.JLabel nup_text1;
    private javax.swing.JLabel nup_text2;
    private javax.swing.JTextField oup;
    private javax.swing.JTextField ous;
    private javax.swing.JLabel position;
    private javax.swing.JPanel up_changer;
    // End of variables declaration//GEN-END:variables
public class passChanger {

        public passChanger() {
            try {
                File passch = new File("D:\\Patan_APP/Admin-control-settings/user.txt");
                try (BufferedReader br = new BufferedReader(new FileReader(passch))) {
                    String brch;
                    brch=br.readLine();
                    br.close();
                    String chec=ous.getText()+oup.getText();
                
                if (brch.equals(chec)) {
                    
                    try (PrintWriter pw = new PrintWriter(passch)) {
                        pw.flush();
                        pw.write(ous + "\n" + nup);
                         pw.close();
                    
            }
                    errch.setForeground(Color.green);
                    errch.setText("Password Changed");
                } else {
                    errch.setForeground(Color.red);
                    errch.setText("wrong data");
                }
                }
            } catch (Exception e) {
                errch.setForeground(Color.red);
                errch.setText("error");
            }
        }
    }

    public class userChanger {

        public userChanger() {
            try{
                File passch = new File("D:\\Patan_APP/Admin-control-settings/user.txt");
           try (BufferedReader br = new BufferedReader(new FileReader(passch))) {
                    String brch;
                    brch=br.readLine();
                    br.close();
                    String chec=ous.getText()+oup.getText();
                
                if (brch.equals(chec)) {
                    
                    try (PrintWriter pw = new PrintWriter(passch)) {
                        pw.flush();
                        pw.write(nup + "\n" + ous);
                         pw.close();
                    
            }
                    errch.setForeground(Color.green);
                    errch.setText("Username Changed");
                } else {
                    errch.setForeground(Color.red);
                    errch.setText("wrong data");
                }
                }
            } catch (Exception e) {
                errch.setForeground(Color.red);
                errch.setText("error");
            }

        }
    }
    class adminProfile
    {
        adminProfile(String user,String pass)
        {
            
        }
    }
}
